theme: jekyll-theme-minimal
title: Crispy Legumes
description: Cool Beans!
show_downloads: false
logo: https://raw.githubusercontent.com/crispylegumes/crispylegumes.github.io/main/CrispyLegumes_512x512.png
